#ifndef VS_ADDRESS_H
#define VS_ADDRESS_H

enum {
    ADDRESS_AVSYNC,
    ADDRESS_FORMAT,
    ADDRESS_FRAMEQ,
    ADDRESS_LOGSET,
    ADDRESS_LOGCONF,
    ADDRESS_LOG,
    ADDRESS_FWLOG,
    ADDRESS_HEVC_CTX,
    ADDRESS_VES,
    ADDRESS_PTS,
};

#endif
